// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.LinkScraper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("linkCount")]
        public long? LinkCount { get; set; }

        [JsonProperty("externalLinkCount")]
        public long? ExternalLinkCount { get; set; }

        [JsonProperty("internalLinkCount")]
        public long? InternalLinkCount { get; set; }

        [JsonProperty("links")]
        public Link[] Links { get; set; }

        [JsonProperty("uniqueDomains")]
        public string[] UniqueDomains { get; set; }

        [JsonProperty("maxLinksReached")]
        public bool? MaxLinksReached { get; set; }
    }

    public partial class Link
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("external")]
        public bool? External { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
